application: psychic-rush-755
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /upload
  script: upload.php
- url: /stylesheets
  static_dir : stylesheets
- url: /images
  static_dir : images
- url: /javascripts
  static_dir : js
- url: /_ah/login_required
  script: do_openid_login.app
- url: /.*
  script: volteServer.php
  login: required
